# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{translate-rails3}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Marklund", "Milan Novota", "Roman Shterenzon"]
  s.date = %q{2011-05-09}
  s.description = %q{This plugin provides a web interface for translating Rails I18n texts
(requires Rails 3.0 or higher) from one locale to another.
The plugin has been tested only with the simple I18n backend that ships
with Rails.
I18n texts are read from and written to YAML files under config/locales.

This gem is a fork of the original https://github.com/mynewsdesk/translate
and also includes work from this fork: https://github.com/milann/translate
}
  s.email = %q{romanbsd@yahoo.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "app/controllers/translate_controller.rb",
    "app/helpers/translate_helper.rb",
    "app/views/layouts/translate.html.erb",
    "app/views/translate/_pagination.html.erb",
    "app/views/translate/index.html.erb",
    "config/routes.rb",
    "init.rb",
    "lib/tasks/translate.rake",
    "lib/translate.rb",
    "lib/translate/file.rb",
    "lib/translate/keys.rb",
    "lib/translate/log.rb",
    "lib/translate/routes.rb",
    "lib/translate/storage.rb",
    "spec/controllers/translate_controller_spec.rb",
    "spec/file_spec.rb",
    "spec/files/translate/app/models/article.rb",
    "spec/files/translate/app/views/category.erb",
    "spec/files/translate/app/views/category.html",
    "spec/files/translate/app/views/category.html.erb",
    "spec/files/translate/app/views/category.rhtml",
    "spec/files/translate/public/javascripts/application.js",
    "spec/keys_spec.rb",
    "spec/log_spec.rb",
    "spec/spec_helper.rb",
    "spec/storage_spec.rb"
  ]
  s.homepage = %q{https://github.com/romanbsd/translate}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Newsdesk translate plugin for Rails 3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ya2yaml>, ["~> 0.30"])
    else
      s.add_dependency(%q<ya2yaml>, ["~> 0.30"])
    end
  else
    s.add_dependency(%q<ya2yaml>, ["~> 0.30"])
  end
end

